name: game_scaffold_dart_example
description: A scaffold for game projects, taking care of server implementation
  and some general events
version: 0.4.0
publish_to: none
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=2.19.0-0 <3.0.0"

dependencies:
  game_scaffold_dart:
    path: ../../dart
  game_scaffold_games:
    path: ../../games
  riverpod: ^2.0.2

dev_dependencies:
  build_runner: ^2.2.1
  dartdoc: ^6.1.2
  test: ^1.21.6
