name: game_scaffold_dart_example
description: A scaffold for game projects, taking care of server implementation
  and some general events
version: 0.5.0-dev
publish_to: none
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  game_scaffold_dart: any
  game_scaffold_games: any
  riverpod: ^2.3.6

dev_dependencies:
  build_runner: ^2.4.5
  dartdoc: ^6.3.0
  test: ^1.24.3

dependency_overrides:
  game_scaffold_dart:
    path: ../
  game_scaffold_games:
    path: ../../games