name: game_scaffold_dart_example
description: A scaffold for game projects, taking care of server implementation
  and some general events
version: 0.5.0-dev
publish_to: none
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=3.10.0 <4.0.0"

resolution: workspace

dependencies:
  game_scaffold_dart: any
  game_scaffold_games: any
  riverpod: 3.0.3