name: game_scaffold_dart_example
description: A scaffold for game projects, taking care of server implementation and some general events
version: 0.2.0+9
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  riverpod: ^0.12.1
  freezed_annotation: ^0.12.0
  json_annotation: ^3.1.1
  game_scaffold_dart: ^0.2.0+9
  game_scaffold_games: ^0.2.0

dev_dependencies:
  json_serializable: any
  freezed: any
  build_runner: any
  test: any
  dartdoc: any