name: game_scaffold_dart_example
description: A scaffold for game projects, taking care of server implementation and some general events
version: 0.3.0
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  riverpod: ^0.13.1
  game_scaffold_dart: ^0.3.0
  game_scaffold_games: ^0.3.0

dev_dependencies:
  build_runner: any
  test: any
  dartdoc: any

dependency_overrides:
  game_scaffold_dart:
    path: ../../dart
  game_scaffold_games:
    path: ../../games
  logging: ^1.0.0
  args: ^2.0.0
  crypto: ^3.0.0
  convert: ^3.0.0
  socket_io_common: ^1.0.0-nullsafety.1