name: game_scaffold_games
description: Games for the game_scaffold_dart package
version: 0.4.1
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=2.19.0-0 <3.0.0"

dependencies:
  collection: ^1.16.0
  fast_immutable_collections: ^7.4.2
  game_scaffold_dart: ^0.4.1+2

