name: game_scaffold_games
description: Games for the game_scaffold_dart package
version: 0.3.0+1
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: '>=2.13.0-0 <3.0.0'

dependencies:
  json_annotation: ^4.0.0
  freezed_annotation: ^0.14.0
  game_scaffold_dart: ^0.3.0
  fast_immutable_collections: ^5.0.0-dev.9

dev_dependencies:
  json_serializable: ^4.1.1
  build_runner: any
  freezed: ^0.14.0

dependency_overrides:
  game_scaffold_dart:
    path: ../dart

scripts:
  - gen: dart run build_runner build --enable-experiment=nonfunction-type-aliases