name: game_scaffold_games
description: Games for the game_scaffold_dart package
version: 0.5.0-dev
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.2
  fast_immutable_collections: ^9.1.5
  freezed_annotation: ^2.2.0
  game_scaffold_dart: ^0.5.0-dev
  json_annotation: ^4.8.1
  

dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
