name: game_scaffold_games
description: Games for the game_scaffold_dart package
version: 0.0.1
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  json_annotation: ^3.1.1
  freezed_annotation: ^0.12.0
  game_scaffold_dart: ^0.1.5

dev_dependencies:
  json_serializable_immutable_collections: 0.4.2
  game_scaffold_test: any
  build_runner: any
  freezed: any
 