name: game_scaffold_games
description: Games for the game_scaffold_dart package
version: 0.4.1
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  collection: ^1.17.0
  fast_immutable_collections: ^8.0.0
  freezed_annotation: ^2.2.0
  game_scaffold_dart: ^0.4.1+2
  json_annotation: ^4.7.0
  

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
