name: game_scaffold_games
description: Games for the game_scaffold_dart package
version: 0.4.0
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  fast_immutable_collections: ^7.0.5-dev0
  freezed_annotation: ^1.0.0
  game_scaffold_dart: ^0.4.0
  json_annotation: ^4.3.0

dev_dependencies:
  build_runner: any
  freezed: ^1.0.0
  json_serializable: ^6.0.1

# dependency_overrides:
#   game_scaffold_dart:
#     path: ../dart
scripts:
  - gen: dart run build_runner build
