name: game_scaffold_games
description: Games for the game_scaffold_dart package
version: 0.3.0
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.0
  freezed_annotation: ^0.14.0
  game_scaffold_dart: "^0.2.0+2"
  fast_immutable_collections: ^2.0.1

dev_dependencies:
  json_serializable_fic: ^0.0.1-nullsafety.0
  build_runner: any
  freezed: ^0.14.0

dependency_overrides:
  game_scaffold_dart:
    path: ../dart
  logging: ^1.0.0
  args: ^2.0.0
  crypto: ^3.0.0
  convert: ^3.0.0
  socket_io_common: ^1.0.0-nullsafety.1


