name: game_scaffold_monorepo

command:
  bootstrap:
    usePubspecOverrides: true

packages:
  - dart/**
  - flutter/**
  - test/**
  - games/**

scripts:
  analyze: melos exec -- exec dart pub global run tuneup check
  postbootstrap: tuneup --version || dart pub global activate tuneup
  postclean: melos exec -- exec rm -rf ./build ./android/.gradle ./ios/.symlinks ./ios/Pods ./android/.idea ./.idea
  test: melos exec --dir-exists=test -- exec flutter test || dart test
  upgrade: melos exec -- exec flutter pub upgrade || dart pub upgrade
  update_analysis: melos exec -- exec cp $MELOS_ROOT_PATH/analysis_options.yaml .
