name: game_scaffold_melos
homepage: https://www.github.com/TimWhiting/game_scaffold
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dev_dependencies:
  melos: ^7.3.0

workspace:
  - dart
  - games
  - flutter
  - test
  - dart/example
  - flutter/example

dependency_overrides:
  # firebase_dart:
  #   git: 
  #     url: https://www.github.com/TimWhiting/firebase_dart
  #     path: packages/firebase_dart
  #     ref: develop
  # firebase_dart_flutter:
  #   git: 
  #     url: https://www.github.com/TimWhiting/firebase_dart
  #     path: packages/firebase_dart_flutter
  #     ref: develop