name: game_scaffold_dart
description: A scaffold for game projects, taking care of server implementation
  and some general events
version: 0.4.1+1
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  characters: ^1.1.0
  collection: ^1.15.0
  enum_to_string: ^2.0.1
  fast_immutable_collections: ^7.0.7-dev0
  freezed_annotation: ^1.0.0
  json_annotation: ^4.3.0
  logging: ^1.0.1
  riverpod: ^1.0.0
  rxdart: ^0.27.1
  socket_io: ^1.0.0
  socket_io_client: ^1.0.0
  stream: ^3.0.2+4

dev_dependencies:
  build_runner: ^2.1.4
  freezed: ^1.0.0
  json_serializable: ^6.0.1
  test: any

scripts:
  - gen: dart run build_runner build
