name: game_scaffold_dart
description: A scaffold for game projects, taking care of server implementation
  and some general events
version: 0.4.1+2
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  characters: ^1.2.1
  collection: ^1.16.0
  enum_to_string: ^2.0.1
  fast_immutable_collections: ^7.4.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  logging: ^1.0.2
  riverpod: ^2.0.2
  rxdart: ^0.27.5
  socket_io: ^1.0.1
  socket_io_client: ^1.0.2
  stream: ^3.0.3

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.1
  test: ^1.21.6

scripts:
  - gen: dart run build_runner build
