name: game_scaffold_dart
description: A scaffold for game projects, taking care of server implementation
  and some general events
version: 0.5.0-dev.1
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  characters: ^1.3.0
  collection: ^1.18.0
  enum_to_string: ^2.0.1
  fast_immutable_collections: ^10.1.1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator:
    git:
      url: https://github.com/rrousselgit/riverpod
      path: packages/riverpod_generator #^3.0.0-dev.11
      ref: dev
  test: ^1.25.2

scripts:
  - gen: dart run build_runner build

dependency_overrides:
  riverpod_analyzer_utils:
    git:
      url: https://github.com/rrousselgit/riverpod
      path: packages/riverpod_analyzer_utils #^3.0.0-dev.11
      ref: dev
  riverpod:
    git:
      url: https://github.com/rrousselgit/riverpod
      path: packages/riverpod #^3.0.0-dev.11
      ref: dev
