name: game_scaffold_dart
description: A scaffold for game projects, taking care of server implementation and some general events
version: 0.1.3+2
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  path: ^1.7.0
  riverpod: ^0.12.1
  freezed_annotation: ^0.12.0
  kt_dart: ^0.8.0
  socket_io: ^0.9.4
  dartz: ^0.9.2
  dartx: ^0.5.0
  json_annotation: ^3.1.1
  stream: ^2.6.0
  logging: ^0.11.4
  socket_io_client: ^0.9.12
  enum_to_string: ^1.0.14

dev_dependencies:
  json_serializable_immutable_collections: 0.4.2
  freezed: 0.12.2
  build_runner: any
  test: any
  dartdoc: any
