name: game_scaffold_dart
description: A scaffold for game projects, taking care of server implementation
  and some general events
version: 0.5.0-dev
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  characters: ^1.3.0
  collection: ^1.17.2
  enum_to_string: ^2.0.1
  fast_immutable_collections: ^9.1.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3
  test: ^1.24.3

scripts:
  - gen: dart run build_runner build

# dependency_overrides:
#   analyzer: ^5.2.0
#   riverpod_analyzer_utils:
#     git:
#       url: https://github.com/TimWhiting/riverpod
#       path: packages/riverpod_analyzer_utils
#       ref: generate_dependencies
#   riverpod_generator:
#     git:
#       url: https://github.com/TimWhiting/riverpod
#       path: packages/riverpod_generator
#       ref: generate_dependencies
