name: game_scaffold_dart
description: A scaffold for game projects, taking care of server implementation and some general events
version: 0.3.0
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  riverpod: ^0.13.1
  freezed_annotation: ^0.14.0
  socket_io: ^0.9.4
  dartx: ^0.6.0
  json_annotation: ^4.0.0
  stream: ^2.6.0
  logging: ^1.0.0
  socket_io_client: ^1.0.0-nullsafety.0
  enum_to_string: ^2.0.0-nullsafety.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  json_serializable: any
  freezed: ^0.14.0
  build_runner: ^1.11.5
  test: any

dependency_overrides:
  logging: ^1.0.0
  socket_io_common: ^1.0.0-nullsafety.1
  crypto: ^3.0.0
  uuid: 3.0.0-nullsafety.0