name: game_scaffold_dart
description: A scaffold for game projects, taking care of server implementation and some general events
version: 0.0.1
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  path: ^1.7.0
  riverpod: any
  freezed_annotation: any
  kt_dart: any
  socket_io: any
  dartz: any
  dartx: any
  socket_io_client: any

dev_dependencies:
  json_serializable_immutable_collections: any
  freezed: any
  build_runner: any
