name: game_scaffold_dart
description: A scaffold for game projects, taking care of server implementation
  and some general events
version: 0.4.1+2
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=2.19.0-0 <3.0.0"

dependencies:
  characters: ^1.2.1
  collection: ^1.17.0
  enum_to_string: ^2.0.1
  fast_immutable_collections: ^8.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  logging: ^1.1.0
  riverpod: ^2.1.1
  riverpod_annotation: ^1.0.6

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  riverpod_generator: ^1.0.6
  test: ^1.22.0

scripts:
  - gen: dart run build_runner build

# dependency_overrides:
#   analyzer: ^5.2.0
#   riverpod_analyzer_utils:
#     git:
#       url: https://github.com/TimWhiting/riverpod
#       path: packages/riverpod_analyzer_utils
#       ref: generate_dependencies
#   riverpod_generator:
#     git:
#       url: https://github.com/TimWhiting/riverpod
#       path: packages/riverpod_generator
#       ref: generate_dependencies
