name: game_scaffold_dart
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  path: ^1.7.0
  riverpod: any
  freezed_annotation: any
  kt_dart: any
  socket_io: any
  dartz: any
  dartx: any
  socket_io_client: any

dev_dependencies:
  json_serializable_immutable_collections: any
  freezed: any
  build_runner: any
