name: example
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.24.0 <4.0.0"
  
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: 0.21.3
  flutter_riverpod: 3.0.3
  game_scaffold: any
  game_scaffold_games: any
  hooks_riverpod: 3.0.3
  logging: 1.3.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
