name: game_scaffold
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: any
  hooks_riverpod: any

  game_scaffold_dart: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
