name: game_scaffold
description: A new Flutter package project.
version: 0.3.0
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^0.13.1
  flutter_riverpod: ^0.13.1
  hooks_riverpod: ^0.13.1
  logging: ^1.0.0
  game_scaffold_dart: ^0.3.0
  flutter_hooks: ^0.16.0
  supabase: ^0.0.1-dev.10
  postgrest: ^0.0.7
  realtime_client: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  dartdoc: any
  game_scaffold_games: any

dependency_overrides:
  game_scaffold_dart:
    path: ../dart
  game_scaffold_games:
    path: ../games
  logging: ^1.0.0
  crypto: ^3.0.0
  convert: ^3.0.0
  socket_io_common: ^1.0.0-nullsafety.1

flutter:
