name: game_scaffold
description: A new Flutter package project.
version: 0.3.3
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=2.13.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_riverpod: ^1.0.0
  game_scaffold_dart: ^0.3.3
  hooks_riverpod: ^1.0.0
  logging: ^1.0.0
  postgrest: ^0.1.8
  realtime_client: ^0.1.11
  riverpod: ^1.0.0
  supabase: ^0.2.7

dev_dependencies:
  dartdoc: any
  flutter_test:
    sdk: flutter
  game_scaffold_games: any

dependency_overrides:
  game_scaffold_dart:
    path: ../dart
  game_scaffold_games:
    path: ../games
flutter: null
