name: game_scaffold
description: A new Flutter package project.
version: 0.0.4+1
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^0.12.1
  flutter_riverpod: ^0.12.1
  hooks_riverpod: ^0.12.1
  game_scaffold_dart: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  dartdoc: any

# dependency_overrides:
#   game_scaffold_dart:
#     path: ../dart

flutter:
