name: game_scaffold
description: Flutter support for a turn based game framework.
version: 0.5.0-dev
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.18.0
  firebase_dart: ^1.1.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.4.10
  game_scaffold_dart: ^0.5.0-dev
  hooks_riverpod: ^2.4.10
  logging: ^1.2.0
  riverpod: ^2.5.0

dev_dependencies:
  dartdoc: ^8.0.5
  flutter_test:
    sdk: flutter
  game_scaffold_games: ^0.5.0-dev

dependency_overrides:
  riverpod_analyzer_utils:
    git:
      url: https://github.com/rrousselgit/riverpod
      path: packages/riverpod_analyzer_utils #^3.0.0-dev.11
      ref: dev
  riverpod:
    git:
      url: https://github.com/rrousselgit/riverpod
      path: packages/riverpod #^3.0.0-dev.11
      ref: dev

flutter: null
