name: game_scaffold
description: A new Flutter package project.
version: 0.4.1
homepage: https://github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_functions: ^3.2.4
  collection: ^1.15.0
  firebase_core: ^1.10.6
  firebase_database: ^9.0.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_riverpod: ^1.0.0
  game_scaffold_dart: ^0.4.1+1
  hooks_riverpod: ^1.0.0
  logging: ^1.0.0
  riverpod: ^1.0.0

dev_dependencies:
  dartdoc: any
  flutter_test:
    sdk: flutter
  game_scaffold_games: any

flutter: null
