name: game_scaffold_dart
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  game_scaffold: any
  riverpod: ^0.12.1
  freezed_annotation: ^0.12.0
  socket_io: ^0.9.4
  dartx: ^0.5.0
  json_annotation: ^3.1.1
  stream: ^2.6.0
  logging: ^0.11.4
  enum_to_string: ^1.0.14

dev_dependencies:
  json_serializable: any
  freezed: any
  build_runner: any
  test: any
  dartdoc: any
  game_scaffold_games: any

