// ignore_for_file: public_member_api_docs, sort_constructors_first, unnecessary_cast, avoid_annotating_with_dynamic, unused_element

import 'package:fast_immutable_collections/fast_immutable_collections.dart';

import 'error.dart';
import 'extensions.dart';
import 'generic.dart';
import 'player.dart';

typedef GameCode = String;
typedef GameType = String;
typedef GameName = String;
typedef PlayerIndex = int;
typedef Rewards = IMap<PlayerID, double>;

extension on Rewards {
  Rewards operator +(Rewards other) =>
      {for (final i in keys) i: this[i]! + other[i]!}.lock;
}

abstract class Event {
  const Event();

  /// Returns the type of the event
  GameType get type;

  /// Returns the player who sent the event
  PlayerID get playerID;

  // Converts the game to JSON
  Map<String, Object?> toJson();
}

base class GamePlayer<E extends Event> {
  GamePlayer({required this.id, required this.name});

  final PlayerID id;
  final PlayerName name;
}

base class GameRound<E extends Event> {
  GameRound({required this.players, required this.currentPlayerIndex});

  /// Returns whether the current round is over, must also be true when the game is over
  /// Checking happens automatically via the macro, this shouldn't be called manually
  bool isOver(GameConfig config) => false;

  /// Calculate the round rewards
  Rewards rewards(GameConfig config) => <PlayerID, double>{}.lock;

  /// Processes the event
  /// This should not move to a end round or new round state,
  ///   instead it should let the game engine move to the next round
  ///   and put itself into a state where `isOver` returns true.
  /// This shouldn't be called manually, as it is processed by the game engine
  MaybeError<GameRound<E>> next(GameConfig config, E event) => error(const GameError(message: 'Not Implemented', player: ''));

  /// Players
  final IList<GamePlayer<E>> players;

  /// The current player index
  final PlayerIndex currentPlayerIndex;


}

base class Game<E extends Event> {
  /// The following definitions are generated by the macro
  Game({required this.type, required this.name, required this.status, required this.rewards
  , required this.round, required this.readyPlayers, required this.players,
  });
  /// A start factory that takes in the user's fields, and optionally also the common fields for non-standard setup,
  /// then finishes the setup, by initializing the type, status, time, rewards, round, currentPlayerIndex etc
  /// The player list should be shuffled prior to the calling their constructor.

  /// Returns the types of the game
  final GameType type;

  /// Returns the game's name
  final GameName name;

  /// Returns the current game status
  final GameStatus status;

  /// Returns the time at which the game changed
  final DateTime time = DateTime.now();

  /// The rewards of the game
  final Rewards rewards;

  final IMap<PlayerID, PlayerName> players;

  /// Ready players
  final ISet<PlayerID> readyPlayers;

  /// The current round
  final int round;

  // Converts the game to JSON
  Map<String, Object?> toJson() => throw UnimplementedError('Unimplemented');

  /// The following definitions need to be implemented by the game author
  /// but in the case of nextRound and next are augmented by the macro
  /// to automatically consider round over and game over conditions and adding rewards

  /// Actually moves the game to a fresh new round
  /// This should not move to an end game state,
  ////  instead it should let the game engine move to the end game
  ///   and put itself into a state where `isOver` returns true.
  /// This shouldn't be called manually, as it is processed by the game engine
  MaybeError<Game<E>> nextRound(GameConfig config) => error(const GameError(message: 'Not Implemented', player: ''));

  /// Returns whether the game is over
  /// Checking happens automatically via the macro, this shouldn't be called manually
  bool isOver(covariant GameRound<E> round, GameConfig config) => false;
}

abstract base class GameFunctions<E extends Event> {
  GameFunctions();
  Game<E> start(GameConfig config, IList<Player> players);
  MaybeError<Game<E>> next(Game<E> game, GameConfig config, E event);
  MaybeError<Game<E>> nextRound(Game<E> game, GameConfig config);
  Game<E> fromJson(JsonMap json);
  E fromJsonE(JsonMap json);
  GameType get gameType;
  GameName get gameName;
}

// ignore: avoid_classes_with_only_static_members
abstract class GameRegistry {
  static final Map<GameType, GameFunctions> _functions = {};
  static GameFunctions _fromType(GameType type) => _functions[type]!;

  static void register<E extends Event>(GameFunctions<E> functions) {
    final type = functions.gameType;
    _functions[type] = functions;
  }

  static Game<E> gameFromJson<E extends Event>(JsonMap json) {
    final type = json['type']! as GameType;
    return functions(type).fromJson(json) as Game<E>;
  }

  static GameFunctions<E> functions<E extends Event>(GameType gameType) =>
      _fromType(gameType) as GameFunctions<E>;

  static E eventFromJson<E>(JsonMap json) {
    final type = json['type']! as GameType;
    return functions(type).fromJsonE(json) as E;
  }

  static String typeName(Game game) => functions(game.type).gameType;

  static Game<E> start<E extends Event>(
          GameConfig config, IList<Player> iList) =>
      functions(config.gameType).start(config, iList.shuffle()) as Game<E>;
}
