name: game_scaffold_test
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  game_scaffold_dart: ^0.0.3
  test: any

dev_dependencies:
  pedantic: ^1.9.0
# dependency_overrides:
#   game_scaffold_dart:
#     path: ../dart
