name: game_scaffold_test
description: A simple command-line application.
version: 0.0.2+1
homepage: https://www.github.com/TimWhiting/game_scaffold

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  game_scaffold_dart: ^0.0.3
  test: ^1.15.7
  meta: ^1.2.4

dev_dependencies:
  pedantic: ^1.9.0
# dependency_overrides:
#   game_scaffold_dart:
#     path: ../dart
